### ISSUE TITLE
Doesn't work with Frusterick Manners?

### ISSUE THREAD

**Issue by wjjessen** [EricMaeker/dokuwiki-plugin-pubmed#1]
I can't seem to get this to work with 2017-02-19e "Frusterick Manners". 

Example:
Code used: {{pubmed>short:24073682}}
Page shows: PMID: 24073682 was not found.

Has anyone reported this? Is there a diagnostic setting so that I can troubleshoot?

**Comment by EricMaeker** [comment]
Hello,

Thank you Walter for your bug report.
Can you please check the page again after a cache removal, and report again.

Eric

**Comment by wjjessen** [comment]
Same result after clearing the cache. The wiki is behind a corporate firewall but don't think that would cause this as I can resolve both pubmedXmlURL and pubmedSearchURL (from classes/_NCBI.php) links in my browser using PMID 24073682. I can also "get($url)" on the server command line and receive xml like this:

curl -H "Accept: application/xml" -H "Content-Type: application/xml" -X GET https://www.ncbi.nlm.nih.gov/pubmed/24073682?report=xml&format=text

**Comment by wjjessen** [comment]
I found this in the php error logs:

PHP Fatal error:  Class 'DOMDocument' not found in /.../wiki/lib/plugins/pubmed/classes/_NCBI.php on line 105
PHP Warning: DOMDocument not found, unable to use sanitizer in /.../wiki/vendor/simplepie/simplepie/library/SimplePie/Sanitize.php on line 271

**Comment by EricMaeker** [comment]
Hello,

May be take a look at this page. Check if the php5-dom is correctly installed and check you PHP version please.

**Comment by wjjessen** [comment]
Was just looking into that. Problem solved. I needed to install the DOM extension. 

For Debian/Ubuntu: sudo apt-get install php5-dom
For Centos/Fedora/Red Hat: yum install php-xml
I had to delete the plugin and reinstall. 

Thanks Eric!

**Comment by EricMaeker** [comment]
Great ! Happyness pubmed 😁

👍

Le jeu. 26 avr. 2018 à 16:59, Walter Jessen <notifications@github.com> a
écrit :
