### ISSUE TITLE
user_defined_output - how to use

### ISSUE THREAD

**Issue by cbso-uc** [EricMaeker/dokuwiki-plugin-pubmed#3]
When I use {{pubmed>user:20413750}} in a page after saving a definition in user_defined_output of Pubmed section in Configuration Manager, I get an error: 

Commands 'user' was not found.
[Available commands]: short, long, long_abstract, summaryXML, clear_summary, remove_dir, search

What is the proper way of doing this? Can you give me an example? I cannot find one in the README.md file

**Comment by EricMaeker** [comment]
Define your user line in the params, define User as default command. Then
remove all command in the pubmed wiki line
{{pubmed>20413750}}

>

**Comment by EricMaeker** [comment]
Updated README.md pushed

>
